package theme

// This file is generated by adwaita_colors_generator.go
// Please do not edit manually, use:
// go generate ./theme/
//
// The colors are taken from: https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.0/named-colors.html

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

var AdwaitaDarkScheme = map[fyne.ThemeColorName]color.Color{
	theme.ColorBlue:                  color.RGBA{0x78, 0xae, 0xed, 0xff},
	theme.ColorGreen:                 color.RGBA{0x8f, 0xf0, 0xa4, 0xff},
	theme.ColorNameBackground:        color.RGBA{0x24, 0x24, 0x24, 0xff},
	theme.ColorNameButton:            color.RGBA{0x30, 0x30, 0x30, 0xff},
	theme.ColorNameError:             color.RGBA{0xff, 0x7b, 0x63, 0xff},
	theme.ColorNameForeground:        color.RGBA{0xff, 0xff, 0xff, 0xff},
	theme.ColorNameInputBackground:   color.RGBA{0x1e, 0x1e, 0x1e, 0xff},
	theme.ColorNameOverlayBackground: color.RGBA{0x38, 0x38, 0x38, 0xff},
	theme.ColorNamePrimary:           color.RGBA{0x35, 0x84, 0xe4, 0xff},
	theme.ColorNameShadow:            color.RGBA{0x0, 0x0, 0x0, 0x5b},
	theme.ColorRed:                   color.RGBA{0xff, 0x7b, 0x63, 0xff},
	theme.ColorYellow:                color.RGBA{0xf8, 0xe4, 0x5c, 0xff},
}

var AdwaitaLightScheme = map[fyne.ThemeColorName]color.Color{
	theme.ColorBlue:                  color.RGBA{0x1c, 0x71, 0xd8, 0xff},
	theme.ColorGreen:                 color.RGBA{0x26, 0xa2, 0x69, 0xff},
	theme.ColorNameBackground:        color.RGBA{0xfa, 0xfa, 0xfa, 0xff},
	theme.ColorNameButton:            color.RGBA{0xeb, 0xeb, 0xeb, 0xff},
	theme.ColorNameError:             color.RGBA{0xc0, 0x1c, 0x28, 0xff},
	theme.ColorNameForeground:        color.RGBA{0x0, 0x0, 0x0, 0xcc},
	theme.ColorNameInputBackground:   color.RGBA{0xff, 0xff, 0xff, 0xff},
	theme.ColorNameOverlayBackground: color.RGBA{0xff, 0xff, 0xff, 0xff},
	theme.ColorNamePrimary:           color.RGBA{0x35, 0x84, 0xe4, 0xff},
	theme.ColorNameShadow:            color.RGBA{0x0, 0x0, 0x0, 0x11},
	theme.ColorRed:                   color.RGBA{0xc0, 0x1c, 0x28, 0xff},
	theme.ColorYellow:                color.RGBA{0xae, 0x7b, 0x3, 0xff},
}
